### ISSUE TITLE
краш

### ISSUE THREAD

**Issue by SignFinder** [KiritoZ-Z/PhantomCore#87]
появляется часто
ос дебиан
Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x40982950 (LWP 12421)]
0x0000000000a5d0d0 in SqlAsyncTask::call (this=<value optimized out>)
   at /data/current/wotlk-x30/src/shared/Database/SqlOperations.h:146
146                 m_op->Execute(m_db);
#0  0x0000000000a5d0d0 in SqlAsyncTask::call (this=<value optimized out>)

   at /data/current/wotlk-x30/src/shared/Database/SqlOperations.h:146
#1  0x0000000000a5cf4c in SqlDelayThread::run (this=0x7fc05ec0d100)

   at /data/current/wotlk-x30/src/shared/Database/SqlDelayThread.cpp:43
#2  0x0000000000a2967a in ACE_Based::Thread::ThreadTask (param=0x7fbfb1d96880)

   at /data/current/wotlk-x30/src/shared/Threading.cpp:183

**Comment by SignFinder** [comment]
sorry is not this core crash
